C     PROGRAM TO CALCULATE THE AREA OF A CIRCLE
C     VARIABLES STARTING WITH I-N ARE INTEGERS BY DEFAULT
C     ALL OTHER STARTING LETTERS ARE REAL NUMBERS BY DEFAULT

      PROGRAM AREA
      REAL RADIUS, AREA, PI
C     EXPLICITLY DECLARE PI AS A PARAMETER (CONSTANT)
      PARAMETER (PI = 3.141592654)

C     PROMPT THE USER FOR INPUT
      WRITE (*,*) 'ENTER THE RADIUS OF THE CIRCLE:'
      READ (*,*) RADIUS

C     CALCULATE THE AREA
      AREA = PI * RADIUS**2

C     DISPLAY THE RESULT
      WRITE (*,*) 'THE AREA IS:', AREA

C     END OF PROGRAM
      END
